---
- name: Checking var now
  fail: msg="The var dogfood must be defined."
  failed_when: dogfood == ""

- name: Debug with var equals
  debug: var=dogfood

- name: Debug with var parameter
  debug:
    var: dogfood

- name: Debug with msg parameter
  debug:
    msg: "Testing msg debug --> {{ dogfood }}"
